### ISSUE TITLE
內野安打會混淆

### ISSUE THREAD

**Issue by teddyyo** [wilsonhsu98/riverside-softball-club#10]
一`(壘方向)`安、二`(壘方向)`安、三`(壘方向)`安會與一壘安打、二壘安打、三壘安打混淆
提幾個建議

- 中文數字大寫
  - 壹安、貳安、叁安
- 統稱內安
  - 內安
- 安打改用阿拉伯數字
  - 一１、二１、三１
- 方位差別顯示
  - `一`安、`二`安、`三`安

**Comment by wilsonhsu98** [comment]
Apply solution1
