### ISSUE TITLE
跑者出局改顏色

### ISSUE THREAD

**Issue by teddyyo** [wilsonhsu98/riverside-softball-club#11]
希望可以在box一眼看出出局是死在壘上或打擊

**Comment by teddyyo** [comment]
跑者因野選出局也算，換句話說只要是滾、飛、犧飛、三振之外的都算

**Comment by wilsonhsu98** [comment]
![Uploading 螢幕快照 2020-03-27 上午12.01.06.png…]()

**Comment by wilsonhsu98** [comment]
![螢幕快照 2020-03-27 上午12 01 06](https://user-images.githubusercontent.com/9699915/77668777-d1a5e100-6fbe-11ea-8de0-f5b3370a87a7.png)
