### ISSUE TITLE
步驟一改成輸入打擊紀錄

### ISSUE THREAD

**Issue by teddyyo** [wilsonhsu98/riverside-softball-club#12]
新增紀錄時，直覺會想要輸入打擊的結果，但現在第一步是先設定壘上跑者，所以每次點開後都要思考一下，這一下可能就無法掌握場上狀況了
希望可以把打擊紀錄移到第一步

**Comment by wilsonhsu98** [comment]
請用mocat登入記錄看看
你是管理者嗎？

**Comment by teddyyo** [comment]
不是
