### ISSUE TITLE
輸入紀錄的畫面顯示打者背號

### ISSUE THREAD

**Issue by teddyyo** [wilsonhsu98/riverside-softball-club#14]
因為當打者是槍手時不認識名字，只知道背號

**Comment by wilsonhsu98** [comment]
![Uploading 螢幕快照 2020-03-27 上午12.01.39.png…]()

**Comment by wilsonhsu98** [comment]
![螢幕快照 2020-03-27 上午12 01 39](https://user-images.githubusercontent.com/9699915/77668704-b935c680-6fbe-11ea-9311-3649a3c2c2fe.png)
