### ISSUE TITLE
「可能在壘上球員」排序反過來

### ISSUE THREAD

**Issue by teddyyo** [wilsonhsu98/riverside-softball-club#16]
實際使用的感覺是愈靠近打者的愈有可能還在壘上

**Comment by teddyyo** [comment]
其實是剛開始還不會設定跑者得分、出局，又遇到大局沒人出局，建議的跑者人數超過五個之後會被藏在卷軸裡面看不到，第一時間找不到人可以按

**Comment by wilsonhsu98** [comment]
![螢幕快照 2020-03-27 上午12 02 12](https://user-images.githubusercontent.com/9699915/77668572-8a1f5500-6fbe-11ea-86f1-152f484a9b8d.png)
![螢幕快照 2020-03-27 上午12 02 20](https://user-images.githubusercontent.com/9699915/77668583-8be91880-6fbe-11ea-98fa-7a8b846d02c7.png)
![螢幕快照 2020-03-27 上午12 02 28](https://user-images.githubusercontent.com/9699915/77668589-8e4b7280-6fbe-11ea-93b1-cae791c02991.png)
