### ISSUE TITLE
輸入紀錄的畫面常駐顯示目前打者資訊

### ISSUE THREAD

**Issue by teddyyo** [wilsonhsu98/riverside-softball-club#17]
現在只有在設定跑者的步驟，才會在本壘看到打者的名字，反而打擊步驟沒有名字
有的時候會停留在打擊步驟較久，例如大家在討論要記安打或失誤之類；需要有打者資訊以確認記錄的對象是正確的

**Comment by wilsonhsu98** [comment]
![螢幕快照 2020-03-27 上午12 01 39](https://user-images.githubusercontent.com/9699915/77668521-78d64880-6fbe-11ea-9762-fe9937018215.png)
